In [49]:
import cv2
import numpy as np

In [50]:
def make_coordinates(image,line_parameters):
    slope,intercept = line_parameters
    y1 = image.shape[0]
    y2 = int(y1*(3/4))
    x1 = int((y1 - intercept)/slope)
    x2 = int((y2 - intercept)/slope)
    return np.array([x1,y1,x2,y2])

In [51]:
def average_slope_intercept(image,lines):
    left_fit = []
    right_fit = []

    for line in lines:
        x1,y1,x2,y2 = line.reshape(4)
        parameters = np.polyfit((x1,x2),(y1,y2),1)
        slope = parameters[0]
        intercept = parameters[1]

        if slope < 0:
            left_fit.append((slope,intercept))
        else:
            right_fit.append((slope,intercept))
    left_fit_average = np.average(left_fit,axis=0)
    right_fit_average = np.average(right_fit,axis=0)

    left_line = make_coordinates(image,left_fit_average)
    right_line = make_coordinates(image,right_fit_average)

    return np.array([left_line,right_line])

In [52]:
def canny(image):
    gray = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5),0)
    canny = cv2.Canny(blur,50,150)  
    return canny

In [53]:
def region_of_interest(image):
    height = image.shape[0]
    polygons = np.array([
        [(200,height),(1100,height),(550,250)]
    ])
    mask = np.zeros_like(image)
    cv2.fillPoly(mask,polygons,255)
    masked_image = cv2.bitwise_and(image,mask)
    return masked_image

In [54]:
def display_lines(image,lines):
    line_image = np.zeros_like(image)
    if lines is not None:
        for line in lines:
            x1,y1,x2,y2 = line.reshape(4)
            cv2.line(line_image,(x1,y1),(x2,y2),(0,255,0),10)
    else:
        print("No Line")
    return line_image

Reading the Image

In [55]:
img = cv2.imread('test_image.jpg')
lane_image = np.copy(img)

In [56]:
canny_image = canny(lane_image) # detect edges
cropped_image = region_of_interest(canny_image)
lines = cv2.HoughLinesP(cropped_image,2,np.pi/180, 100,np.array([]),minLineLength=40, maxLineGap=5)
print(lines)
average_lines = average_slope_intercept(lane_image,lines)
line_image = display_lines(lane_image,average_lines)
combo_image = cv2.addWeighted(lane_image,0.8,line_image,1,1)
cv2.imshow("Image",combo_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[704 418 927 641]]

 [[704 426 766 490]]

 [[320 703 445 494]]

 [[592 304 704 416]]

 [[617 333 660 377]]

 [[767 493 969 702]]

 [[585 301 704 424]]

 [[402 542 455 460]]

 [[660 373 754 467]]]


In [57]:
cap = cv2.VideoCapture(r"D:\vs code\python\DeepLearning\Projects\lane_detection\test4.mp4")

while True:
    _,lane_image = cap.read()
    canny_image = canny(lane_image)
    cropped_image = region_of_interest(canny_image)
    try:
        lines = cv2.HoughLinesP(cropped_image,2,np.pi/180, 100,np.array([]),minLineLength=40, maxLineGap=5)
        average_lines = average_slope_intercept(lane_image,lines)
        line_image = display_lines(lane_image,average_lines)
        combo_image = cv2.addWeighted(lane_image,0.8,line_image,1,1)
        cv2.imshow("image",combo_image)
    except:
        print("No Lane Lines")

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()

C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_sl

No Lane Lines


C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_slope_intercept(lane_image,lines)
C:\Users\adity\AppData\Local\Temp\ipykernel_9372\975091912.py:9: RankWarning: Polyfit may be poorly conditioned
  average_lines = average_sl